INFO     custom_logger:test_login.py:112 ************ test_login_positive2 STARTED ************
ERROR    custom_logger:test_login.py:136 ************ test_login_positive2 FAILED ************